apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-node
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: hello-node
    spec:
      containers:
      - image: hello-node:v1
        name: hello-node
        ports:
        - containerPort: 8080
          protocol: TCP
